// Fill out your copyright notice in the Description page of Project Settings.


#include "SActionComponent.h"
#include "SAction.h"
#include "../action_roguelike.h"
#include "Net/UnrealNetwork.h"
#include "Engine/ActorChannel.h"


// Sets default values for this component's properties
USActionComponent::USActionComponent()
{
  // Set this component to be initialized when the game starts, and to be ticked every frame.  You can turn these features
  // off to improve performance if you don't need them.
  PrimaryComponentTick.bCanEverTick = true;

  SetIsReplicatedByDefault( true );
}


void USActionComponent::ServerStartAction_Implementation( AActor* Instigator, FName ActionName )
{
  StartActionByName( Instigator, ActionName );
}


void USActionComponent::AddAction( AActor* Instigator, TSubclassOf<USAction> ActionClass )
{
  if( !ensure( ActionClass ) )
  {
    return;
  }

  USAction* NewAction{ NewObject<USAction>( GetOwner(), ActionClass)};
  if( ensure( NewAction ) )
  {
    NewAction->Initialize( this );

    Actions.Add( NewAction );

    if( NewAction->bAutoStart && ensure( NewAction->CanStart( Instigator ) ) )
    {
      NewAction->StartAction( Instigator );
    }
  }
}


void USActionComponent::RemoveAction( USAction* ActionToRemove )
{
  if( ensure( ActionToRemove && !ActionToRemove->IsRunning() ) )
  {
    return;
  }

  Actions.Remove( ActionToRemove );
}


bool USActionComponent::StartActionByName( AActor* Instigator, FName ActionName )
{
  for( USAction* Action : Actions )
  {
    if( Action && ( Action->ActionName == ActionName ) )
    {
      if( !Action->CanStart( Instigator ) )
      {
        FString FailedMsg( FString::Printf( TEXT( "Failed to run: %s" ), *ActionName.ToString() ) );
        GEngine->AddOnScreenDebugMessage( -1, 2.0f, FColor::Red, FailedMsg );
        continue;
      }

      // Is Client?
      if( GetOwner()->HasAuthority() )
      {
        ServerStartAction( Instigator, ActionName );
      }

      Action->StartAction( Instigator );
      return true;
    }
  }

  return false;
}


bool USActionComponent::StopActionByName( AActor* Instigator, FName ActionName )
{
  for( USAction* Action : Actions )
  {
    if( Action && ( Action->ActionName == ActionName ) )
    {
      if( Action->IsRunning() )
      {
        Action->StopAction( Instigator );
        return true;
      }
    }
  }

  return false;
}


// Called when the game starts
void USActionComponent::BeginPlay()
{
  Super::BeginPlay();

  if( GetOwner()->HasAuthority() )
  {
    for( TSubclassOf<USAction> ActionClass : DefaultActions )
    {
      AddAction( GetOwner(), ActionClass );
    }
  }
}


// Called every frame
void USActionComponent::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
  Super::TickComponent( DeltaTime, TickType, ThisTickFunction );

  //FString DebugMsg{ GetNameSafe( GetOwner() ) + " : " + ActiveGameplayTags.ToStringSimple() };
  //GEngine->AddOnScreenDebugMessage( -1, 0.0f, FColor::White, DebugMsg );

  // Draw All Actions
  for( USAction* Action : Actions )
  {
    FColor TextColor{ Action->IsRunning() ? FColor::Blue : FColor::White };
    FString ActionMsg{ FString::Printf( TEXT( "[%s] Action %s " ), *GetNameSafe( GetOwner() ), *GetNameSafe( Action ) ) };
    LogOnScreen( this, ActionMsg, TextColor, 0.0f );
  }
}


bool USActionComponent::ReplicateSubobjects( UActorChannel* Channel, FOutBunch* Bunch, FReplicationFlags* RepFlags )
{
  bool bWroteSomething{ Super::ReplicateSubobjects( Channel, Bunch, RepFlags ) };
  for( USAction* Action : Actions )
  {
    if( Action )
    {
      bWroteSomething |= Channel->ReplicateSubobject( Action, *Bunch, *RepFlags );
    }
  }

  return bWroteSomething;
}


void USActionComponent::GetLifetimeReplicatedProps( TArray<class FLifetimeProperty>& OutLifetimeProps ) const
{
  Super::GetLifetimeReplicatedProps( OutLifetimeProps );
  DOREPLIFETIME( USActionComponent, Actions );
}
